const {test}=require('node:test');const assert=require('node:assert/strict');
const {redefineSketchPlane}=require('../src/lib/features/redefineSketchPlane.ts');
const {serializeProject,parseProject}=require('../src/lib/project/nativeFormat.ts');
const {localToWorldPoint}=require('../src/lib/replicad/plane.ts');
const {useFeatureStore}=require('../src/lib/features/store.ts');
const {useSketchStore}=require('../src/lib/sketch/store.ts');
const {undoModel,redoModel}=require('../src/lib/history/store.ts');
test('redefine preserves local geometry and dimensions, stores the new plane, and supports undo/redo',async()=>{
 const originalPlane={origin:[0,0,0],normal:[0,0,1],xDir:[1,0,0]};
 const target={origin:[0,20,0],normal:[0,1,0],xDir:[1,0,0]};
 const sketch={id:'s',type:'sketch',label:'Esboço',plane:originalPlane,shapes:[{id:'c',type:'circle',center:'p',radius:3}],points:{p:{id:'p',x:5,y:7}},dimensions:[],constraints:[],fixedPointIds:['p'],profileWires:[['c']]};
 const operation={id:'e',type:'extrude',label:'Original',plane:originalPlane,profile:{kind:'circle',cx:5,cy:7,r:3},depth:10};
 const clickedElsewhere={origin:[100,-80,0],normal:[0,0,-1],xDir:[0,1,0]};
 const preserved=redefineSketchPlane([sketch,operation],'s',clickedElsewhere,{preserveWorldPosition:true});
 assert.deepEqual(preserved[0].plane,originalPlane);
 assert.equal(preserved[0].points,sketch.points);
 assert.equal(preserved[0].shapes,sketch.shapes);
 assert.deepEqual(localToWorldPoint(preserved[0].plane,sketch.points.p),localToWorldPoint(originalPlane,sketch.points.p));
 assert.throws(()=>redefineSketchPlane([sketch],'s',target,{preserveWorldPosition:true}),/não é coplanar/);
 assert.throws(()=>redefineSketchPlane([sketch],'s',{...originalPlane,origin:[0,0,5]},{preserveWorldPosition:true}),/não é coplanar/);
 const original=[sketch,operation];const updated=redefineSketchPlane(original,'s',target);
 assert.equal(updated[0].shapes,sketch.shapes);assert.equal(updated[0].points,sketch.points);
 assert.equal(updated[0].dimensions,sketch.dimensions);assert.equal(updated[0].constraints,sketch.constraints);
 assert.deepEqual(updated[0].profileWires,sketch.profileWires);assert.equal(updated[1],operation);
 assert.deepEqual(original[0].plane,originalPlane);
 assert.deepEqual(localToWorldPoint(updated[0].plane,{x:5,y:7}),[5,20,-7]);
 assert.deepEqual(parseProject(serializeProject(updated)).features[0].plane,target);
 assert.throws(()=>redefineSketchPlane(original,'missing',target),/não encontrado/);
 assert.throws(()=>redefineSketchPlane(original,'s',{...target,xDir:[0,1,0]}),/inválido/);
 useFeatureStore.setState({features:original});useSketchStore.setState({activePlane:originalPlane});await Promise.resolve();
 useFeatureStore.setState({features:updated});useSketchStore.setState({activePlane:target});await Promise.resolve();
 undoModel();assert.deepEqual(useFeatureStore.getState().features[0].plane,originalPlane);assert.deepEqual(useSketchStore.getState().activePlane,originalPlane);
 redoModel();assert.deepEqual(useFeatureStore.getState().features[0].plane,target);assert.deepEqual(useSketchStore.getState().activePlane,target);
});
